version: "3.1"

services:
  flask-app:
    build:
      context: ./src
      dockerfile: Dockerfile

    environment:
      - STATUS=${STATUS}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_AVATAR=${DEFAULT_AVATAR}

    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/wopien.crt:/etc/nginx/ssl/wopien.crt:ro
      - ./nginx/ssl/wopien.key:/etc/nginx/ssl/wopien.key:ro

    depends_on:
      - flask-app

    ports:
      - "443:443"

  pgadmin:
    image: ${PGADMIN}

    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    ports:
      - "5050:80"



