version: "3.1"

services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      - STATUS=Production
      - DATABASE_URL=postgresql://hvicqihaayikto:8fa070cf2c64080953c8776cf5f159dee79bb31f0c9e0505530c144e9f4d955c@ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/df5dkfh47cnp78
      - SECRET_KEY=\xac\x96\xe9\xeb 4\xb5\x7f\xdd\x93

    ports:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - flask-app

    ports:
      - "80:80"


